"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "answers",
      [
        {
          answer: "John",
          correct: false,
          questionId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Dave",
          correct: true,
          questionId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Liam",
          correct: false,
          questionId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Olivia",
          correct: false,
          questionId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "A Nanny",
          correct: true,
          questionId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Elijah",
          correct: false,
          questionId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Charlotte",
          correct: false,
          questionId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Ava",
          correct: false,
          questionId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Annie Munston",
          correct: true,
          questionId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Annie Jackson",
          correct: false,
          questionId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Annie Smith",
          correct: false,
          questionId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Annie Braddock",
          correct: false,
          questionId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Freaky Friday",
          correct: false,
          questionId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Sleepover",
          correct: false,
          questionId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Mean Girls",
          correct: true,
          questionId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Slee Over",
          correct: false,
          questionId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "70's",
          correct: false,
          questionId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "80's",
          correct: true,
          questionId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "60's",
          correct: false,
          questionId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "90's",
          correct: false,
          questionId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Kearny High In San Diego",
          correct: false,
          questionId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Diane Keaton",
          correct: true,
          questionId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Colonel Lucas",
          correct: false,
          questionId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Olivia",
          correct: false,
          questionId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Monster's Ball",
          correct: true,
          questionId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Sanaa Lathan ",
          correct: false,
          questionId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Julia Roberts",
          correct: false,
          questionId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Natalie Cole",
          correct: false,
          questionId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Mr. Jingles",
          correct: false,
          questionId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Mr.Dave",
          correct: true,
          questionId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Mr.Liam",
          correct: false,
          questionId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Ms.Emma",
          correct: false,
          questionId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Carrie",
          correct: false,
          questionId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Christine",
          correct: true,
          questionId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Cujo",
          correct: false,
          questionId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Silver Bullet",
          correct: false,
          questionId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "George Reeves",
          correct: false,
          questionId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "William Shatner",
          correct: true,
          questionId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Leonard Nimoy",
          correct: false,
          questionId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Mark Hamill",
          correct: false,
          questionId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Friday the 13th",
          correct: true,
          questionId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "American Gothic",
          correct: false,
          questionId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "House of 1000 Corpses",
          correct: false,
          questionId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "The Evil Dead",
          correct: false,
          questionId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "K Mart",
          correct: false,
          questionId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Wal Mart",
          correct: false,
          questionId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "CVS",
          correct: false,
          questionId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "S Mart",
          correct: true,
          questionId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "James Bond",
          correct: false,
          questionId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Ash Williams",
          correct: false,
          questionId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Madison Lee",
          correct: true,
          questionId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Robocop",
          correct: false,
          questionId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "5",
          correct: false,
          questionId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "4",
          correct: true,
          questionId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "2",
          correct: false,
          questionId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "3",
          correct: false,
          questionId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answer: "Total Recall",
          correct: false,
          questionId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "True Lies",
          correct: false,
          questionId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "The Terminator",
          correct: true,
          questionId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Conan The Barbarian",
          correct: false,
          questionId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Blue Pill",
          correct: false,
          questionId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Neither",
          correct: false,
          questionId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Both",
          correct: false,
          questionId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answer: "Red Pill",
          correct: true,
          questionId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("answers", null, {});
  },
};
